### ISSUE TITLE
catalog breaks on subfolders

### ISSUE THREAD

**Issue by Devineavenger** [shane-mason/FieldStation42#18]
last commit does not work for subfolders

OSError: MoviePy error: failed to read the duration of file catalog/station1/movie/mkv.
catalog/station1/movie/mkv: Is a directory

Traceback (most recent call last):
  File "*******station_42.py", line 258, in <module>
    station = Station42(c, args.rebuild_catalog)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*******station_42.py", line 22, in __init__
    self.catalog = ShowCatalog(self.config, rebuild_catalog=rebuild_catalog)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*******catalog.py", line 38, in __init__
    self.build_catalog()
  File "*******catalog.py", line 88, in build_catalog
    self.clip_index[tag] = self._process_media(file_list, tag)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*******catalog.py", line 55, in _process_media
    raise Exception(f"Error processing video {fname}")
Exception: Error processing video catalog/station1/movie/mkv

Just add the . back 

    def _find_media(self, path):
        file_list = []
        for ext in self.supported_formats:
            print(f"{path}/*.{ext}")
            file_list += glob.glob(f"{path}/*.{ext}")
        return file_list

also you broke subfolders
add sub not tag_dir

            #now check for sub directories one layer deep
            subs = [ f.path for f in os.scandir(tag_dir) if f.is_dir() ]
            for sub in subs:
                self._l.info("Found sub-directory " + sub)
                file_list = self._find_media(sub)
                self.clip_index[tag] += self._process_media(file_list, tag)

test before commit

**Comment by shane-mason** [comment]
>test before commit

I am going to ask you one last time: stop talking to me like I work for you. 

You may not be aware of how you are coming across, but it is very off-putting, so I wanted to go ahead and be straight forward with you: this is an open source project that I work on in my very small amount of spare time and I am not here to be ordered around by, well, anyone. This is supposed to be a fun and relaxing hobby - not a day job. I don't tell you what you must do, or how you must do it, so please talk to me with the same respect I use when I talk to you.

The issue is corrected.
